apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fluentd-buffer-pvc
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: default
